# Generated by Django 6.0.1 on 2026-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_active_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='So we can contact you on WhatsApp', max_length=15)),
                ('idea_description', models.TextField(help_text='Describe the colors, flowers, or theme you want.')),
                ('reference_image', models.ImageField(blank=True, help_text='Upload a screenshot or photo of what you want.', null=True, upload_to='custom_requests/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
